a, b, c = map(float, input().split(" "))
print("TRIANGULO: {:.3f}".format((1.0/2)*a*c))
print("CIRCULO: {:.3f}".format(3.14159*(c*c)))
print("TRAPEZIO: {:.3f}".format((1.0/2)*(a+b)*c))
print("QUADRADO: {:.3f}".format((b*b)))
print("RETANGULO: {:.3f}".format((a*b)))